version = 1

test_patterns = ["test/**"]

exclude_patterns = ["examples/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "6"
  module_system = "commonjs"
  environment = [
    "browser",
    "nodejs"
  ]